sim:
	vcs -R +v2k -full64 tb.v \
	./falcon.v \
	./ram_behav/bram2x128.v \
	./ram_behav/bram4x128.v \
	./ram_behav/bram8x128.v \
	./ram_behav/bram16x128.v \
	./ram_behav/bram32x128.v \
	./ram_behav/bram64x128.v \
	./ram_behav/bram128x128.v \
	./ram_behav/bram256x128.v \
	./ram_behav/bram512x128.v \
	./ram_behav/bram1024x128.v \
	./ram_behav/bram1024x16.v \
	-debug_acc +nospecify +define+FSDB

	